### PR TITLE
Update rspec.rb

### PR DESCRIPTION
**Pull request by Overload119**
Removes the dependency on RSpec.

### CODE REVIEW

**Comment by technicalpickles** [comment]
Are you seeing an error that this fixes? There is already a guard clause here:

https://github.com/rubyatscale/singed/blob/ee1c84d7a76eee595ac58c5e5f5b04785d8c2458/lib/singed.rb#L56

**Comment by Overload119** [comment]
Yes, this is the error I'm seeing:

```
bundle exec rails c
/Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/singed-0.1.1/lib/singed/rspec.rb:3:in `<main>': undefined method `configure' for RSpec:Module (NoMethodError)

RSpec.configure do |config|
     ^^^^^^^^^^
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/singed-0.1.1/lib/singed.rb:56:in `<main>'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/runtime.rb:55:in `each'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/runtime.rb:44:in `each'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/runtime.rb:44:in `require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler.rb:195:in `require'
	from /Users/amirsharif/Projects/halo/config/application.rb:7:in `<main>'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:22:in `require_application!'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands/console/console_command.rb:101:in `perform'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/amirsharif/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by Overload119** [comment]
This is after adding this gem to `development` group.

**Comment by kivanio** [comment]
@Overload119 that was my original issue.
To make It works it needs to be at same group as `rspec-rails` 
In general it is in `test` group.

I think we follow same steps:
1 - put at `development` because it does not need to run at CI or in test.
2 - It broken the load
3 - I put at `test` group with `rspec-rails` and then it works.

**Comment by technicalpickles** [comment]
Looking more closely at the error, I don't believe the change in this PR would fix it:

```
Undefined method `configure' for RSpec:Module (NoMethodError)
```

It would need to check for `configure` on it as well. That is what I said in the last comment, but wanted to make sure to connect it to the error message you reported.

**Comment by technicalpickles** [comment]
Handling this slightly differently in https://github.com/rubyatscale/singed/pull/15

**Pull request closed without merging**
